document.write( '<div class=\"silex-pages\">\n' );
document.write( '        <div data-silex-type=\"image\" class=\"editable-style silex-id-hamburger-menu image-element menu-button prevent-draggable hide-on-desktop\">\n' );
document.write( '            <img alt=\"open mobile menu\" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAoCAYAAAC8cqlMAAAB5UlEQVR42u2ZPWvCUBSGM+UfFO3e3dLu/QN+oKj4EUXRQREEJYgoiCAu6qCogyDo7iJ21UUaKqEgCC4iiEMGB3UVgsnpTWj/wfVK2nvhGbKEPJyT996TMMzPGg6H5mKx+GgkyuWyeTQasb8OTDwef4tEIp8+n+/LYIjJZJJHQiwzm81M6OLDarWqNpsNjEYgEJCy2ewT0+/3TagighElNFAnQT6ft1ARKkJFqMgfFvF4PFpuEwFtdrcRqVarIIoirFYrIiyXSxiPx+B2u/GJBINBuF6vQHopigK1Wg2fCMdxcLlciIuoqgqNRgOfiN1uB3Qwg91uB8fjkQiHwwEmkwne1qLxS0VuKKJle71eh06nQ4Rmswk8z+MVcTqdsNlsQJZlotF7Pp8hk8ngE4lGo/qN7xG/vV4Pb0Xm8zlxkdPpBGgMx/+yJxIJKBQKRMjlcuBwOGhq/Q+RcDgMsViMCFrAuFwu/CKDwQC22y1IkkSE/X4PgiDo+xc2Ea0S9zjGa/Hb7Xbxifj9fj0K7yFSqVTwtlY6nYbpdKpPiSRYLBbQarX0PYymFhWhIlSEilCRW6GdyUqlkoVZr9dsKpXiOY6TtW+7BkNBz/7ebrcf9L+6Xq+XRYPMMyrTq5EIhUIvaAjTJb4BBNQ2yhnth0wAAAAASUVORK5CYII=\" class=\"silex-element-content\">\n' );
document.write( '        </div>\n' );
document.write( '\n' );
document.write( '        <a id=\"page-page-1\" data-silex-type=\"page\" class=\"page-element\" href=\"index.html\">Page 1</a><a id=\"page-moto-x3m\" data-silex-type=\"page\" class=\"page-element\" href=\"moto-x3m.html\">Moto X3M</a><a id=\"page-strike-force-heroes\" data-silex-type=\"page\" class=\"page-element\" href=\"strike-force-heroes.html\">Strike Force Heroes</a><a id=\"page-gun-mayhem\" data-silex-type=\"page\" class=\"page-element\" href=\"gun-mayhem.html\">Gun Mayhem</a><a id=\"page-rogue-soul-2\" data-silex-type=\"page\" class=\"page-element\" href=\"rogue-soul-2.html\">Rogue Soul 2</a><a id=\"page-alex-stream\" data-silex-type=\"page\" class=\"page-element\" href=\"alex-stream.html\">alex stream</a><a id=\"page-dbz-devolution\" data-silex-type=\"page\" class=\"page-element\" href=\"dbz-devolution.html\">DBZ Devolution</a><a id=\"page-chat-\" data-silex-type=\"page\" class=\"page-element\" href=\"chat-.html\">Chat </a><a id=\"page-prodigy\" data-silex-type=\"page\" class=\"page-element page-link-active\" href=\"prodigy.html\">Prodigy</a><a id=\"page-crazy-plant-shop\" data-silex-type=\"page\" class=\"page-element\" href=\"crazy-plant-shop.html\">Crazy Plant Shop</a><a id=\"page-super-smash-flash-2\" data-silex-type=\"page\" class=\"page-element\" href=\"super-smash-flash-2.html\">Super Smash Flash 2</a><a id=\"page-news\" data-silex-type=\"page\" class=\"page-element\" href=\"news.html\">News</a><a id=\"page-mngs\" data-silex-type=\"page\" class=\"page-element\" href=\"mngs.html\">MNGS</a><a id=\"page-mngs-order-to-pickup\" data-silex-type=\"page\" class=\"page-element\" href=\"mngs-order-to-pickup.html\">MNGS Order to Pickup</a><a id=\"page-about\" data-silex-type=\"page\" class=\"page-element\" href=\"about.html\">About</a><a id=\"page-copyright-application\" data-silex-type=\"page\" class=\"page-element\" href=\"copyright-application.html\">Copyright Application</a><a id=\"page-run-3-\" data-silex-type=\"page\" class=\"page-element\" href=\"run-3-.html\">Run 3 </a><a id=\"page-cat-ninja\" href=\"cat-ninja.html\" data-silex-type=\"page\" class=\"page-element\">Cat Ninja</a></div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    \n' );
document.write( '    \n' );
document.write( '    \n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '<div data-silex-type=\"container\" class=\"prevent-draggable container-element editable-style silex-id-1478366444112-1 section-element\" style=\"\">\n' );
document.write( '        <div data-silex-type=\"container\" class=\"editable-style silex-element-content silex-id-1478366444112-0 silex-container-content container-element prevent-draggable website-width\"><div data-silex-type=\"html\" class=\"editable-style silex-id-1545614796221-2 html-element\" style=\"\"><div class=\"silex-element-content\">\n' );
document.write( '<div id=\"quickstart-account-details\"></div>\n' );
document.write( '<div id=\"quickstart-sign-in\"></div>\n' );
document.write( '<div id=\"quickstart-sign-in-status\"></div></div></div><div data-silex-type=\"image\" class=\"editable-style silex-id-1544632522128-3 image-element page-prodigy paged-element page-link-active\" style=\"\"><img src=\"../../ytbrosweb/master/LogoMakr_1T9uGG.png\" class=\"silex-element-content\"></div></div>\n' );
document.write( '    </div><div data-silex-type=\"container\" class=\"prevent-draggable container-element editable-style silex-id-1474394621033-3 section-element\" style=\"\">\n' );
document.write( '        <div data-silex-type=\"container\" class=\"editable-style silex-element-content silex-id-1474394621032-2 silex-container-content container-element prevent-draggable website-width\"><div data-silex-type=\"html\" class=\"editable-style silex-id-1544632325753-2 html-element page-prodigy paged-element page-link-active\" style=\"\"><div class=\"silex-element-content\"><div id=\"container\">\n' );
document.write( '  <iframe src="https://games.ytbros.tk/prodigygame.html" width=\"1000" height=\"900" data-silex-iframe-src="https://ytbros.tk/prodigygame.html\"></iframe> \n' );
document.write( '  \n' );
document.write( '  \n' );
document.write( '    <button class=\"button\" onclick=\"fullscreenChange()\"><img src=\"https://cdn2.iconfinder.com/data/icons/user-interface-46/256/menu_fullscreen-512.png\" width=\"50\" height=\"50\"></button>\n' );
document.write( '  </div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '  <script type=\"text/javascript\">\n' );
document.write( '  {\n' );
document.write( '  var button = document.querySelector(\'#container .button\');\n' );
document.write( 'button.addEventListener(\'click\', fullscreen);\n' );
document.write( '// when you are in fullscreen, ESC and F11 may not be trigger by keydown listener. \n' );
document.write( '// so don\'t use it to detect exit fullscreen\n' );
document.write( 'document.addEventListener(\'keydown\', function (e) {\n' );
document.write( '  console.log(\'key press\' + e.keyCode);\n' );
document.write( '});\n' );
document.write( '// detect enter or exit fullscreen mode\n' );
document.write( 'document.addEventListener(\'webkitfullscreenchange\', fullscreenChange);\n' );
document.write( 'document.addEventListener(\'mozfullscreenchange\', fullscreenChange);\n' );
document.write( 'document.addEventListener(\'fullscreenchange\', fullscreenChange);\n' );
document.write( 'document.addEventListener(\'MSFullscreenChange\', fullscreenChange);\n' );
document.write( 'function fullscreen() {\n' );
document.write( '  // check if fullscreen mode is available\n' );
document.write( '  if (document.fullscreenEnabled || \n' );
document.write( '    document.webkitFullscreenEnabled || \n' );
document.write( '    document.mozFullScreenEnabled ||\n' );
document.write( '    document.msFullscreenEnabled) {\n' );
document.write( '    \n' );
document.write( '    // which element will be fullscreen\n' );
document.write( '    var iframe = document.querySelector(\'#container iframe\');\n' );
document.write( '    // Do fullscreen\n' );
document.write( '    if (iframe.requestFullscreen) {\n' );
document.write( '      iframe.requestFullscreen();\n' );
document.write( '    } else if (iframe.webkitRequestFullscreen) {\n' );
document.write( '      iframe.webkitRequestFullscreen();\n' );
document.write( '    } else if (iframe.mozRequestFullScreen) {\n' );
document.write( '      iframe.mozRequestFullScreen();\n' );
document.write( '    } else if (iframe.msRequestFullscreen) {\n' );
document.write( '      iframe.msRequestFullscreen();\n' );
document.write( '    }\n' );
document.write( '  }\n' );
document.write( '  else {\n' );
document.write( '    document.querySelector(\'.error\').innerHTML = \'You cannot fullscreen with this browser/computer. If you are in Ms.Blair class in ********* (school name blocked for privacy reasons), see the maker of this website.\';\n' );
document.write( '  }\n' );
document.write( '}\n' );
document.write( 'function fullscreenChange() {\n' );
document.write( '  if (document.fullscreenEnabled ||\n' );
document.write( '       document.webkitIsFullScreen || \n' );
document.write( '       document.mozFullScreen ||\n' );
document.write( '       document.msFullscreenElement) {\n' );
document.write( '    console.log(\'enter fullscreen\');\n' );
document.write( '  }\n' );
document.write( '  else {\n' );
document.write( '    console.log(\'exit fullscreen\');\n' );
document.write( '  }\n' );
document.write( '  // force to reload iframe once to prevent the iframe source didn\'t care about trying to resize the window\n' );
document.write( '  // comment this line and you will see\n' );
document.write( '  var iframe = document.querySelector(\'iframe\');\n' );
document.write( '  iframe.src = iframe.src;\n' );
document.write( '}\n' );
document.write( '}\n' );
document.write( '</script>\n' );
document.write( '<div id=\"disqus_thread\"></div>\n' );
document.write( '<script type=\"text/javascript\">\n' );
document.write( '/**\n' );
document.write( '*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.\n' );
document.write( '*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/\n' );
document.write( '/*\n' );
document.write( 'var disqus_config = function () {\n' );
document.write( 'this.page.url = https://ytbros.tk/#!page-prodigy;  // Replace PAGE_URL with your page\'s canonical URL variable\n' );
document.write( 'this.page.identifier = prodigy4321; // Replace PAGE_IDENTIFIER with your page\'s unique identifier variable\n' );
document.write( '};\n' );
document.write( '*/\n' );
document.write( '(function() { // DON\'T EDIT BELOW THIS LINE\n' );
document.write( 'var d = document, s = d.createElement(\'script\');\n' );
document.write( 's.src = \'https://games4u-3.disqus.com/embed.js\';\n' );
document.write( 's.setAttribute(\'data-timestamp\', +new Date());\n' );
document.write( '(d.head || d.body).appendChild(s);\n' );
document.write( '})();\n' );
document.write( '</script>\n' );
document.write( '<noscript>Please enable JavaScript to view the &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;lt;a href=\"https://disqus.com/?ref_noscript\"&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;gt;comments powered by Disqus.&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;lt;/a&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;gt;</noscript>\n' );
document.write( '<script id=\"dsq-count-scr\" src=\"https://games4u-3.disqus.com/count.js\" async=\"\" type=\"text/javascript\"></script>\n' );
document.write( '                            \n' );
document.write( '\n' );
document.write( '\n' );
document.write( '</div></div></div>\n' );
document.write( '    </div><div data-silex-type=\"html\" class=\"editable-style silex-id-1542730020762-1 html-element\" style=\"\" title=\"Games4U \"><div class=\"silex-element-content\">Pages\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/moto-x3m\">Moto X3M</a>\n' );
document.write( '</button>\n' );
document.write( '\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/strike-force-heroes\">Strike Force Heroes</a>\n' );
document.write( '</button>\n' );
document.write( '\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/gun-mayhem\">Gun Mayhem</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/rogue-soul-2\">Rogue Soul 2</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/\">Home</a>\n' );
document.write( '</button>\n' );
document.write( '\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/alex-mixer-stream\">Alex Mixer Stream</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/dbz-devolution\">DBZ Devolution</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/chat\">Chat</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/prodigy\">Prodigy</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/super-smash-flash-2\">Super Smash Flash 2 (finally!)</a>\n' );
document.write( '</button>\n' );
document.write( '\n' );
document.write( '<button>\n' );
document.write( ' <a href=\"/cat-ninja\">Cat Ninja</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '    \n' );
document.write( '    <a href=\"run-3-.html\">Run 3</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '    <a href=\"/news\">News</a>\n' );
document.write( '</button></div></div>' );
