
document.write( '   <div class=\"silex-pages\">\n' );
document.write( '        <div data-silex-type=\"image\" class=\"editable-style silex-id-hamburger-menu image-element menu-button prevent-draggable hide-on-desktop\">\n' );
document.write( '            <img alt=\"open mobile menu\" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAoCAYAAAC8cqlMAAAB5UlEQVR42u2ZPWvCUBSGM+UfFO3e3dLu/QN+oKj4EUXRQREEJYgoiCAu6qCogyDo7iJ21UUaKqEgCC4iiEMGB3UVgsnpTWj/wfVK2nvhGbKEPJyT996TMMzPGg6H5mKx+GgkyuWyeTQasb8OTDwef4tEIp8+n+/LYIjJZJJHQiwzm81M6OLDarWqNpsNjEYgEJCy2ewT0+/3TagighElNFAnQT6ft1ARKkJFqMgfFvF4PFpuEwFtdrcRqVarIIoirFYrIiyXSxiPx+B2u/GJBINBuF6vQHopigK1Wg2fCMdxcLlciIuoqgqNRgOfiN1uB3Qwg91uB8fjkQiHwwEmkwne1qLxS0VuKKJle71eh06nQ4Rmswk8z+MVcTqdsNlsQJZlotF7Pp8hk8ngE4lGo/qN7xG/vV4Pb0Xm8zlxkdPpBGgMx/+yJxIJKBQKRMjlcuBwOGhq/Q+RcDgMsViMCFrAuFwu/CKDwQC22y1IkkSE/X4PgiDo+xc2Ea0S9zjGa/Hb7Xbxifj9fj0K7yFSqVTwtlY6nYbpdKpPiSRYLBbQarX0PYymFhWhIlSEilCRW6GdyUqlkoVZr9dsKpXiOY6TtW+7BkNBz/7ebrcf9L+6Xq+XRYPMMyrTq5EIhUIvaAjTJb4BBNQ2yhnth0wAAAAASUVORK5CYII=\" class=\"silex-element-content\">\n' );
document.write( '        </div>\n' );
document.write( '\n' );
document.write( '        <a id=\"page-page-1\" data-silex-type=\"page\" class=\"page-element\" href=\"index.html\">Page 1</a><a id=\"page-moto-x3m\" data-silex-type=\"page\" class=\"page-element\" href=\"moto-x3m.html\">Moto X3M</a><a id=\"page-strike-force-heroes\" data-silex-type=\"page\" class=\"page-element\" href=\"strike-force-heroes.html\">Strike Force Heroes</a><a id=\"page-gun-mayhem\" data-silex-type=\"page\" class=\"page-element\" href=\"gun-mayhem.html\">Gun Mayhem</a><a id=\"page-rogue-soul-2\" data-silex-type=\"page\" class=\"page-element\" href=\"rogue-soul-2.html\">Rogue Soul 2</a><a id=\"page-alex-stream\" data-silex-type=\"page\" class=\"page-element\" href=\"alex-stream.html\">alex stream</a><a id=\"page-dbz-devolution\" data-silex-type=\"page\" class=\"page-element\" href=\"dbz-devolution.html\">DBZ Devolution</a><a id=\"page-chat-\" data-silex-type=\"page\" class=\"page-element\" href=\"chat-.html\">Chat </a><a id=\"page-prodigy\" data-silex-type=\"page\" class=\"page-element\" href=\"prodigy.html\">Prodigy</a><a id=\"page-crazy-plant-shop\" data-silex-type=\"page\" class=\"page-element\" href=\"crazy-plant-shop.html\">Crazy Plant Shop</a><a id=\"page-super-smash-flash-2\" data-silex-type=\"page\" class=\"page-element\" href=\"super-smash-flash-2.html\">Super Smash Flash 2</a><a id=\"page-news\" data-silex-type=\"page\" class=\"page-element\" href=\"news.html\">News</a><a id=\"page-mngs\" data-silex-type=\"page\" class=\"page-element\" href=\"mngs.html\">MNGS</a><a id=\"page-mngs-order-to-pickup\" data-silex-type=\"page\" class=\"page-element\" href=\"mngs-order-to-pickup.html\">MNGS Order to Pickup</a><a id=\"page-about\" data-silex-type=\"page\" class=\"page-element\" href=\"about.html\">About</a><a id=\"page-copyright-application\" data-silex-type=\"page\" class=\"page-element\" href=\"copyright-application.html\">Copyright Application</a><a id=\"page-run-3-\" data-silex-type=\"page\" class=\"page-element page-link-active\" href=\"run-3-.html\">Run 3 </a><a id=\"page-cat-ninja\" href=\"cat-ninja.html\" data-silex-type=\"page\" class=\"page-element\">Cat Ninja</a></div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    \n' );
document.write( '    \n' );
document.write( '    \n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '<div data-silex-type=\"container\" class=\"prevent-draggable container-element editable-style silex-id-1478366444112-1 section-element\" style=\"\">\n' );
document.write( '        <div data-silex-type=\"container\" class=\"editable-style silex-element-content silex-id-1478366444112-0 silex-container-content container-element prevent-draggable website-width\"><div data-silex-type=\"html\" class=\"editable-style silex-id-1545614796221-2 html-element\" style=\"\"><div class=\"silex-element-content\">\n' );
document.write( '<div id=\"quickstart-account-details\"></div>\n' );
document.write( '<div id=\"quickstart-sign-in\"></div>\n' );
document.write( '<div id=\"quickstart-sign-in-status\"></div></div></div><div data-silex-type=\"image\" class=\"editable-style silex-id-1548768659805-3 image-element page-run-3- paged-element page-link-active\" style=\"\"><img src=\"/LogoMakr_1T9uGG.png\" class=\"silex-element-content\"></div></div>\n' );
document.write( '    </div><div data-silex-type=\"container\" class=\"prevent-draggable container-element editable-style silex-id-1474394621033-3 section-element\" style=\"\">\n' );
document.write( '        <div data-silex-type=\"container\" class=\"editable-style silex-element-content silex-id-1474394621032-2 silex-container-content container-element prevent-draggable website-width\"><div data-silex-type=\"html\" class=\"editable-style silex-id-1548768679317-4 html-element page-run-3- paged-element page-link-active\" style=\"\"><div class=\"silex-element-content\"><object id=\"GameEmbedSWF\" width=\"100%\" height=\"600\" data=\"https://run3free.com//data/file/swf/run3.swf\" type=\"application/x-shockwave-flash\"><param name=\"base\" value=\"\"><param name=\"wmode\" value=\"direct\"><param name=\"movie\" value=\"https://run3free.com//data/file/swf/run3.swf\"><param name=\"menu\" value=\"false\"><param name=\"allowNetworking\" value=\"internal\"><param name=\"allowScriptAccess\" value=\"never\"><embed src=\"https://run3free.com//data/file/swf/run3.swf\" menu=\"false\" allownetworking=\"internal\" allowscriptaccess=\"never\" width=\"100%\" height=\"100%\" type=\"application/x-shockwave-flash\"></object>\n' );
document.write( '</div></div></div>\n' );
document.write( '    </div><div data-silex-type=\"html\" class=\"editable-style silex-id-1542730020762-1 html-element\" style=\"\" title=\"Games4U \"><div class=\"silex-element-content\">Pages\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/moto-x3m\">Moto X3M</a>\n' );
document.write( '</button>\n' );
document.write( '\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/strike-force-heroes\">Strike Force Heroes</a>\n' );
document.write( '</button>\n' );
document.write( '\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/gun-mayhem\">Gun Mayhem</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/rogue-soul-2\">Rogue Soul 2</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/\">Home</a>\n' );
document.write( '</button>\n' );
document.write( '\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/alex-mixer-stream\">Alex Mixer Stream</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/dbz-devolution\">DBZ Devolution</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/chat\">Chat</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/prodigy\">Prodigy</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '<a href=\"/super-smash-flash-2\">Super Smash Flash 2 (finally!)</a>\n' );
document.write( '</button>\n' );
document.write( '\n' );
document.write( '<button>\n' );
document.write( ' <a href=\"/cat-ninja\">Cat Ninja</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '    \n' );
document.write( '    <a href=\"run-3-.html\">Run 3</a>\n' );
document.write( '</button>\n' );
document.write( '<button>\n' );
document.write( '    <a href=\"/news\">News</a>\n' );
document.write( '</button></div></div>\n' );
document.write( '    \n' );

